"""Database models and connection for the weather trading bot."""
from datetime import datetime
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Date, Boolean, JSON, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import inspect

from backend.config import settings

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in settings.DATABASE_URL else {}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Trade(Base):
    """Simulated trades for tracking P&L."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    event_slug = Column(String, nullable=True)
    market_type = Column(String, default="weather", index=True)

    # Trade details
    direction = Column(String)  # "yes" or "no"
    entry_price = Column(Float)
    size = Column(Float)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Settlement
    settled = Column(Boolean, default=False)
    settlement_time = Column(DateTime, nullable=True)
    settlement_value = Column(Float, nullable=True)  # 1.0=Yes won, 0.0=No won
    result = Column(String, default="pending")  # pending, win, loss
    pnl = Column(Float, nullable=True)

    # Model performance tracking
    model_probability = Column(Float)
    market_price_at_entry = Column(Float)
    edge_at_entry = Column(Float)
    confidence = Column(Float, nullable=True)  # z-score-derived confidence at entry (see weather_signals.py)

    # Maker limit order tracking
    execution_type  = Column(String,   nullable=True)  # "maker_limit", "timed_out"
    order_id        = Column(String,   nullable=True)  # Kalshi order UUID
    limit_price     = Column(Float,    nullable=True)  # resting bid price (0–1)
    order_placed_at = Column(DateTime, nullable=True)  # when order was submitted
    order_status    = Column(String,   nullable=True)  # "pending_fill", "filled", "cancelled", "timed_out"

    # Trailing-stop tracking (position_liquidator_job, scheduler.py). Highest
    # unrealised gain_pct observed for this open position since entry; None
    # until the liquidator has evaluated it at least once. Monotonically
    # non-decreasing while open — lets the exit logic detect a retracement
    # from peak instead of only a flat profit-target level.
    peak_gain_pct = Column(Float, nullable=True)

    # Settlement provenance + reconciliation (2026-08-20). "official" =
    # settle_pending_trades()'s real Kalshi API resolution — already ground
    # truth, never needs reconciling. "nws_early" = force-settled off a live
    # NWS observation crossing EXIT_BUFFER_F before Kalshi has officially
    # resolved (see weather_signals.py's "settlement" exit_type) — a
    # projection, not a certainty, so it's checked against the real result
    # once available. "trend_stop" = a real market sale at the live bid, not
    # a projection — already a realized transaction, nothing to reconcile.
    settlement_source = Column(String, nullable=True)
    reconciled_at = Column(DateTime, nullable=True)          # when checked against the official result
    reconciliation_mismatch = Column(Boolean, nullable=True)  # True if the early call disagreed with it


class BotState(Base):
    """Bot state and statistics."""
    __tablename__ = "bot_state"

    id = Column(Integer, primary_key=True)
    bankroll = Column(Float, default=10000.0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    last_run = Column(DateTime, nullable=True)
    is_running = Column(Boolean, default=False)

    # Live-mode session tracking — set once on the first live-mode boot, then
    # preserved across restarts so the dashboard can filter to only live trades.
    live_session_start = Column(DateTime, nullable=True)   # UTC of first live boot
    live_start_balance = Column(Float, nullable=True)       # Kalshi balance at that moment


class Signal(Base):
    """Trading signals generated by the bot."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    market_type = Column(String, default="weather", index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    direction = Column(String)
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    sources = Column(JSON)
    reasoning = Column(String)

    executed = Column(Boolean, default=False)

    # Calibration tracking — filled after settlement
    actual_outcome = Column(String, nullable=True)    # "yes" or "no"
    outcome_correct = Column(Boolean, nullable=True)
    settlement_value = Column(Float, nullable=True)     # 1.0=Yes won, 0.0=No won
    settled_at = Column(DateTime, nullable=True)


class AILog(Base):
    """Log of all AI API calls."""
    __tablename__ = "ai_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    provider = Column(String, index=True)
    model = Column(String)

    prompt = Column(String)
    response = Column(String)
    call_type = Column(String, index=True)

    latency_ms = Column(Float)
    tokens_used = Column(Integer)
    cost_usd = Column(Float)

    related_market = Column(String, nullable=True)
    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


class ScanLog(Base):
    """Log of each market scan run."""
    __tablename__ = "scan_logs"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(String, unique=True, index=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    categories_scanned = Column(JSON)
    platforms_scanned = Column(JSON)

    markets_found = Column(Integer, default=0)
    signals_generated = Column(Integer, default=0)
    trades_executed = Column(Integer, default=0)

    ai_calls_made = Column(Integer, default=0)
    ai_cost_usd = Column(Float, default=0.0)

    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


class ModelForecastLog(Base):
    """
    Per-model raw forecast log — one row per (city, model, fetch), used to
    compute rolling per-model accuracy (see backend/data/weather.py's
    get_model_weights). Deliberately separate from Signal.reasoning, which
    only stores the already-BLENDED effective mean: down-weighting a model
    that's currently running warm/cold requires each model's own number,
    not the combined one.

    Rows are cheap and append-only; the weighting function reads only the
    latest row per (city_key, model_name, target_date) within its lookback
    window, mirroring the "last prediction per date wins" pattern already
    used by get_recent_bias.
    """
    __tablename__ = "model_forecast_log"

    id = Column(Integer, primary_key=True, index=True)
    city_key = Column(String, index=True)
    target_date = Column(Date, index=True)
    model_name = Column(String, index=True)  # "gfs" (incl. HRRR-blended), "ecmwf", "nws"
    predicted_high_f = Column(Float)
    logged_at = Column(DateTime, default=datetime.utcnow, index=True)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)
    ensure_schema()


def ensure_schema():
    """Ensure newer schema fields exist even if migration wasn't run."""
    inspector = inspect(engine)
    try:
        columns = [col["name"] for col in inspector.get_columns("trades")]
    except Exception:
        return

    if "event_slug" not in columns:
        stmt = "ALTER TABLE trades ADD COLUMN event_slug VARCHAR"
        if engine.dialect.name not in ("sqlite", "mysql"):
            stmt = "ALTER TABLE trades ADD COLUMN IF NOT EXISTS event_slug VARCHAR"

        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text(stmt))

    if "market_type" not in columns:
        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text("ALTER TABLE trades ADD COLUMN market_type VARCHAR DEFAULT 'weather'"))

    # Root-caused 2026-08-20: "DATETIME" is a SQLite/MySQL type name, not a
    # valid Postgres one — Postgres wants "TIMESTAMP". Every DATETIME column
    # in this loop was silently failing to add itself on Postgres (the
    # broad except below swallows it as "column already exists" style
    # noise). order_placed_at only actually exists on the live table
    # because it happened to already be in the model when the table was
    # first created via Base.metadata.create_all() (dialect-aware, unlike
    # this raw-SQL fallback) — this exact ALTER TABLE path had never
    # actually been exercised for a DATETIME column until reconciled_at
    # below silently failed to appear. Same dialect check bot_state already
    # uses further down, just applied here too.
    dt_type = "TIMESTAMP" if engine.dialect.name == "postgresql" else "DATETIME"

    for col, coltype in [
        ("execution_type",  "TEXT"),
        ("order_id",        "TEXT"),
        ("limit_price",     "REAL"),
        ("order_placed_at", dt_type),
        ("order_status",    "TEXT"),
        ("confidence",      "REAL"),
        ("peak_gain_pct",   "REAL"),
        ("settlement_source",       "TEXT"),
        ("reconciled_at",           dt_type),
        ("reconciliation_mismatch", "BOOLEAN"),
    ]:
        if col not in columns:
            with engine.connect() as conn:
                try:
                    with conn.begin():
                        conn.execute(text(f"ALTER TABLE trades ADD COLUMN {col} {coltype}"))
                except Exception:
                    pass  # column already exists

    # Add live-mode tracking columns to bot_state table
    try:
        state_columns = [col["name"] for col in inspector.get_columns("bot_state")]
    except Exception:
        state_columns = []

    if state_columns:
        is_pg = engine.dialect.name == "postgresql"
        dt_sql = "TIMESTAMP" if is_pg else "DATETIME"
        with engine.connect() as conn:
            for col, coltype in [
                ("live_session_start", dt_sql),
                ("live_start_balance",  "FLOAT"),
            ]:
                if col not in state_columns:
                    try:
                        with conn.begin():
                            conn.execute(text(f"ALTER TABLE bot_state ADD COLUMN {col} {coltype}"))
                    except Exception:
                        pass

    # Add calibration columns to signals table
    try:
        signal_columns = [col["name"] for col in inspector.get_columns("signals")]
    except Exception:
        signal_columns = []

    if signal_columns:
        with engine.connect() as conn:
            for col, coltype in [
                ("actual_outcome", "TEXT"),
                ("outcome_correct", "BOOLEAN"),
                ("settlement_value", "FLOAT"),
                ("settled_at", "DATETIME"),
                ("market_type", "VARCHAR DEFAULT 'weather'"),
            ]:
                if col not in signal_columns:
                    try:
                        with conn.begin():
                            conn.execute(text(f"ALTER TABLE signals ADD COLUMN {col} {coltype}"))
                    except Exception:
                        pass  # column already exists


def get_db():
    """Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
